### ISSUE TITLE
troubles monitoring IBM V7000

### ISSUE THREAD

**Issue by amanogue** [H-Software/Zabbix-II#1]
I'm trying to monitor 2 IBM V7000 with "_Special_Storwize_Perf" template.
I've followed the installation instructions and the configuration steps. 
The logs files are full of errors. I'm stuck on this problem, I don't know where else to look for. 

jue abr  9 12:55:01 CEST 2015
Can't load cache: [Errno 2] No such file or directory: '/var/cache/zabbix/svc_perf.cczv3700_CPD1.cache'
Connecting to cczv3700_CPD1
Can't load cache: [Errno 2] No such file or directory: '/var/cache/zabbix/svc_perf.cczv3700_CPD1.cache'
Connecting to cczv3700_CPD1
Traceback (most recent call last):
  File "/etc/zabbix/externalscripts/svc_perf_wbem.py", line 200, in <module>
    collectStats(conn, 'volume', 'IBMTSSVC_StorageVolume', 'IBMTSSVC_StorageVolumeStatistics', VOLUME_COUNTERS)
  File "/etc/zabbix/externalscripts/svc_perf_wbem.py", line 106, in collectStats
    names = enumNames(elementClass)
  File "/etc/zabbix/externalscripts/svc_perf_wbem.py", line 53, in enumNames
    for obj in conn.ExecQuery( 'WQL', 'SELECT DeviceID, ElementName FROM %s' % (cimClass) ):
  File "/usr/lib/python2.6/site-packages/pywbem/cim_operations.py", line 522, in ExecQuery
    Query = Query)
  File "/usr/lib/python2.6/site-packages/pywbem/cim_operations.py", line 168, in imethodcall
    verify_callback = self.verify_callback)
  File "/usr/lib/python2.6/site-packages/pywbem/cim_http.py", line 225, in wbem_request
    raise AuthError(response.reason)
pywbem.cim_http.AuthError: Unauthorized

Thanks in advance.
Antonio.

**Comment by ghost** [comment]
Hey, 
i have nearly the same problem.

Traceback (most recent call last):
  File "/usr/share/zabbix/externalscripts/svc_perf_discovery.py", line 59, in <module>
    volumes = conn.ExecQuery('WQL', 'select DeviceID, ElementName from IBMTSSVC_StorageVolume')
  File "/usr/local/lib/python2.7/dist-packages/pywbem-0.7.0-py2.7.egg/pywbem/cim_operations.py", line 522, in ExecQuery
    Query = Query)
  File "/usr/local/lib/python2.7/dist-packages/pywbem-0.7.0-py2.7.egg/pywbem/cim_operations.py", line 168, in imethodcall
    verify_callback = self.verify_callback)
  File "/usr/local/lib/python2.7/dist-packages/pywbem-0.7.0-py2.7.egg/pywbem/cim_http.py", line 225, in wbem_request
    raise AuthError(response.reason)
pywbem.cim_http.AuthError: Unauthorized

The "cannot load cache" can be fixt if you change the path to a existing path.

Have you found a Solution?

Geetings

Sententiosus

**Comment by czhujer** [comment]
This is problem with authentication and python library wbem.. (https://pypi.python.org/pypi/pywbem)
zabbix script just uses this..

I'm not able debug python code. Sory guys :)
